name: Docker Build and Push to Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 你如果推 tag，GitHub Actions 会自动得到 ${{ github.ref_name }}。
        # git tag v1.2.3
        # git push origin v1.2.3
      - name: Set VERSION env
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # 推荐用PAT而非密码
          password: ${{ secrets.DOCKER_HUB_TOKEN }} 
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfile # Dockerfile所在目录
          file: Dockerfile # 指定Dockerfile路径
          push: true # 启用推送
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ env.VERSION }} 


